@startuml Class Diagram
  !define DARKSTYLE
  !include style.puml

  class Signal {
    -int signal_value_
    -char signal_type_

    -int ReadSignalValue()
    -bool InitHX711()
    -long ReadHX711()
    -void RequestError()
    +int get_signal_value()
    +bool InitSignal()
  }

  class HX711 {
    -byte PD_SCK
    -byte DOUT
    -byte GAIN
    -long OFFSET
    -float SCALE

    +void begin()
    +bool is_ready()
    +void wait_ready()
    +bool wait_ready_retry()
    +bool wait_ready_timeout()
    +void set_gain()
    +long read()
    +long read_average()
    +double get_value()
    +float get_units()
    +void tare()
    +void set_scale()
    +float get_scale()
    +void set_offset()
    +long get_offset()
    +void power_down()
    +void power_up()
  }

  interface Arduino {
    +available()
    +availableForWrite()
    +begin()
    +end()
    +find()
    +findUntil()
    +flush()
    +parseFloat()
    +parseInt()
    +peek()
    +print()
    +println()
    +read()
    +readBytes()
    +readBytesUntil()
    +readString()
    +readStringUntil()
    +setTimeout()
    +write()
    +serialEvent()
  }

  Arduino -- Signal
  Signal ..> HX711
@enduml