@startuml Sequence Diagram
  !define DARKORANGE
  !include style.puml
  skinparam actorStyle awesome
  skinparam SequenceBoxBorderColor #Blue

  actor SimRacer as "Sim Racer"

  box "Arduino Pedalbox"
  participant ConvertAD as "HX711 Library"
  participant Signal
  participant SerialCommunication as "Serial Communication"
  end box
  actor SimPC as "Sim PC"

  'start sequence
  == Braking ==

  SimRacer -> ConvertAD : brake pedal force
  ConvertAD -> Signal : digital measurement
  Signal -> SerialCommunication : brake measurement
  SerialCommunication -> SimPC : brake input signal
  SimPC --> SimRacer : decceleration

@enduml