@startuml Use Case Diagram
  !define LIGHTORANGE
  !include style.puml

  skinparam actorStyle awesome
  left to right direction

  actor SimRacer as "Sim Racer"
  actor SimPC as "Sim PC"

  rectangle "Arduino Pedalbox" {
    package Pedalbox {
      usecase Brake as "Push brake pedal" <<Use Case>>
      usecase ADConvert as "convert signal A/D" <<Use Case>>
    }
    package ArduinoBox {
      usecase ReadSignal as "Read signal" <<Use Case>>
      usecase ReceiveSignal as "Receive game \ncontroller input" <<Use Case>>
    }

    SimRacer -- Brake
    Brake ..> ReadSignal : <<include>>
    ADConvert ..> ReadSignal : <<extend>>
    ReceiveSignal -- SimPC
  }
@enduml