#pragma once

#define BRAKE_PEDAL_DOUT 10
#define BRAKE_PEDAL_SCK 9
#define BRAKE_PEDAL_OFFSET 12000

#define THROTTLE_PEDAL_PIN A0
#define THROTTLE_PEDAL_OFFSET 0

#define CLUTCH_PEDAL_PIN A1
#define CLUTCH_PEDAL_OFFSET 0